### ISSUE TITLE
Add unit-tests configuration

### ISSUE THREAD

**Issue by birthdaysgift** [fenya123/bingin#10]
**As an Architect I would like to have all code in the backend codebase to be covered by unit-tests. To make it possible we need to have pytest and coverage tools to be set up for the backend repository.**

**Acceptance criteria**

- pytest is set up to run tests
- pytest is set up to measure code coverage
- coverage is set up to fail if it's under 100%
- coverage is set up to check branch coverage
- coverage setup allows to exclude some lines from coverage
- `README.md` has instructions how to run tests and get coverage reports
- repository has POC test which will prove that pytest and coverage work fine

**Tasks:**

- [x] https://github.com/fenya123/acih-backend/issues/7

**Quickfixes**

- [x] https://github.com/fenya123/acih-backend/issues/11
- [x] https://github.com/fenya123/acih-backend/issues/14
