### ISSUE TITLE
Add CI pipeline

### ISSUE THREAD

**Issue by birthdaysgift** [fenya123/bingin#11]
**As an Architect I would like to prevent code with errors from linters / tests / coverage to be merged into "develop" branch. I would like to have CI pipeline to be set up for the backend repository and prevent PR merging if it has any errors.**

To make our CI setup to be portable to any CI platform other than GitHub, we need to have additional isolation level - all CI stuff should be isolated in docker containers on top of GitHub isolation level - Runners. Why do we need this? Because even if GitHub Runners have the same isolation level as docker containers, and if we decide to use GitHub Runners without docker then we will not be able to use our GitHub Workflow scripts if we will want to change CI engine at some time. So to make it portable we need to pack almost all logic to the docker containers and use GitHub Runner only for running our containers.

Also, this additional isolation level will allow us to not depend on GitHub Runners configuration, for example if GitHub Runner configuration will change at some time it may broke our CI builds because we expect Runner to have one configuration but it has changed it to another.

Let's look at some examples.

Here is the GitHub Workflow which runs mypy and doesn't use Docker isolation.
```yaml
on: [push]
jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code 
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest
        run: mypy
```

This workflow contains all the logic in the workflow file itself - python version, command for installing dependencies, command for running mypy.

Compare it with dockerized version:

```yaml
on: [push]
jobs:
  mypy:
    name: Mypy
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build mypy container
        run: docker compose --file envs/ci/lint/docker-compose.yml build mypy

      - name: Run mypy container
        run: docker compose --file envs/ci/lint/docker-compose.yml run mypy
```

The second workflow keeps all of those logic hidden in docker-compose and Dockerfile files. The workflow knows nothing about which python version we use, which dependencies we install and how we do it. It knows only that we build and run a container. All logic is hidden from it. This approach will allow us to easily move this "build container - run container" logic to any other CI system.

Additional advantage of this approach is that we can use our docker setup to test it locally at first, before trying to debug on the CI platform. It will potentially decrease debugging time we spend on GitHub platform.

These two links may be a good starting point for understanding how GitHub Actions works:
[Quickstart](https://docs.github.com/en/actions/quickstart)
[Understanding GitHub Actions](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions)

One more thing we would like to run in our CI pipeline except from linters is a lock-file consitency check from poetry:
```bash
poetry lock --check
```

**Tasks BE**

- [x] https://github.com/fenya123/acih-backend/issues/9
- [x] https://github.com/fenya123/acih-backend/issues/12

**Tasks FE**

- [x] https://github.com/fenya123/acih-frontend/issues/9
- [x] https://github.com/fenya123/acih-frontend/issues/16
