### ISSUE TITLE
CI pipeline optimizations

### ISSUE THREAD

**Issue by birthdaysgift** [fenya123/bingin#12]
**As an Architect I would like to increase our CI pipeline performance to get linters/tests response as soon as possible. It will make our development cycle shorter, allow developers to get CI reports in a reasonable amount of time and not wait for too long to know what's exactly prevents them to merge their code.**

- Docker build process can be optimized by caching intermediate build layers in GitHub Cache. We need this because now all container build stuff is happened in each CI pipeline run.

  <details><summary>Details</summary>
  <p>
  Each time when a new commit is added to the branch CI pipeline build process does all stuff:

  - install system dependencies
  - install project dependencies
  - copy source files

  First step is always the same for each run. The second step may be different, but only for a small amount of commits (actually updating project dependencies happens very rare).

  So we don't want to waste CI time for doing the same things over and over. It would be better if we would be able to cache them. This will allow us to decrease CI pipeline run time for each tool we run - mypy, ruff, flake8, pylint, pytest.
  
  </p>
  </details> 

- Different linters have their own ways to gain run performance. We need to leverage those abilities to make our CI runs to be as fast as possible:
  - flake8 doesn't have anything which could improve its performance
  - pylint has option `--jobs` which we can use to specify number of parallel processes
  - mypy has a cache directory `.mypy_cache`
  - ruff has a cache directory `.ruff_cache`
  - pytest has a cache directory `.pytest_cache`

**Tasks:**

- [x] https://github.com/fenya123/acih-backend/issues/17
- [x] https://github.com/fenya123/acih-backend/issues/19

**Quickfixes**

- [x] https://github.com/fenya123/acih-backend/issues/33
- [x] https://github.com/fenya123/acih-backend/issues/35
