### ISSUE TITLE
CI pipeline cleaning up

### ISSUE THREAD

**Issue by birthdaysgift** [fenya123/bingin#13]
**As an Architect I would like to have only relevant CI pipeline runs in repository Actions tab. It will allow the team to easily navigate between different runs if it will be needed to investigate some issue in the code or in the pipeline itself.**

We use rebase strategy to work with git branches. It means that each feature branch at the end of the work is rebased on top of the last version of develop branch and contains only one commit with description of what has been done for this feature. When developers work with their feature branches they push a lot of "work in progress" commits, and each commit pushed to the feature branch triggers new GitHub workflow run. But since all of these commits will be rewritten and squashed at the end we want to keep our workflow runs list clean and don't contain previous runs which were triggered by commits that don't exist after rebase.

Also we want to clean up old workflow runs for deleted branches. There is no sense to keep these runs, because they are related to nonexistent commits from nonexistent branches. More than that, since runs of this workflow will remain after each deleted branch we want to clean them up as well. It means that we will always have only one run of this workflow - the run for the most recent deleted branch.

In the scope of this task we need to create a workflow which does following things:

1. removes runs for nonexistent commits after branch deleting
2. removes runs for nonexistent commits after branch force pushing
3. removes runs created during steps 1 and 2

**Tasks**

- [x] https://github.com/fenya123/acih-backend/issues/21
- [x] https://github.com/fenya123/acih-backend/issues/25
- [x] https://github.com/fenya123/acih-backend/issues/22
- [x] https://github.com/fenya123/acih-backend/issues/27
- [x] https://github.com/fenya123/acih-backend/issues/29
