### ISSUE TITLE
Add PostgreSQL

### ISSUE THREAD

**Issue by birthdaysgift** [fenya123/bingin#15]
**As an Architect I would like to have PostgreSQL being used as main database for backend application.**

Before we start to write the implementation of the backend we have to setup main tools we want to use and check that they work correctly. The goal of this story is setting up PostgreSQL and configuring for all environments (local, ci) and tools (linters, pytest) we use at this moment.

**Acceptance criteria**

- PostgreSQL is added to the repo via docker and docker-compose to local/dev, local/test and ci/test environments
- sqlalchemy and other dependencies needed to work with postgres from python code are added to the repo as dependencies
- sqlalchemy is configured and allows us to connect to db from our code
- alembic is added to the repo as a dependency and configured to work with migrations for our database
- simple model and endpoint are added to check that postgresql works fine in local
- simple test is written for that endpoint to check that unit-testing is works fine in local and ci
- README.md is updated and reflects all required changes related to postgresql

**Tasks**

- [x] https://github.com/fenya123/acih-backend/issues/37
- [x] https://github.com/fenya123/acih-backend/issues/41
- [x] https://github.com/fenya123/acih-backend/issues/43
- [x] https://github.com/fenya123/acih-backend/issues/45
- [x] https://github.com/fenya123/acih-backend/issues/47
- [x] https://github.com/fenya123/acih-backend/issues/49
- [x] https://github.com/fenya123/acih-backend/issues/51
- [x] https://github.com/fenya123/acih-backend/issues/53
- [x] https://github.com/fenya123/acih-backend/issues/59
- [x] https://github.com/fenya123/acih-backend/issues/57

**Comment by birthdaysgift** [comment]
Approximate approach to story decomposition:

- postgres in local (containers, volumes)
- setup postgres connection for our python code (sqlachemy - engine, session, Base)
  - simple model is added
  - from python interactive shell we can:
    - create tables based on sqlalchemy model
    - create new object of that model and commit it
    - query created object
    - remove created object
    - drop created table
- alembic 
  - initialize alembic for project
  - connect alembic to database
  - create migration for Entity model
- configure fastapi to work with database
  - endpoint which adds object to db
  - endpoint which gets list of objects from db
  - possible acceptance criteria:
    ```bash
    # requests below should be executed on empty database
    
    # create entity with id 42
    curl --request POST http://localhost:8000/entities/42
    
    # create entity with id 18
    curl --request POST http://localhost:8000/entities/18
    
    
    # get entities with ids 42 and 18
    curl --request GET http://localhost:8000/entities
    
    ```
- integration with pytest
  - separate environment for testing (`envs/local/test`)
  - tests for `create_entity` and `get_entities` routes
  - transact session for db fixtures
- add config object and get rid of hardcoded values
  (config object will get values from environment variables, parse and validate them; app will use values from this config object; different env variables for different environments will be provided via `.env` files)
- add postgres to ci

<details><summary>Skiped for now</summary>
<p>
due to lack of time, we can definitely do it later

- configuration for pytest (`fixtures` fixture, `set_autoincrement_counters`)
- checks for alembic (hooks, formatting etc.)

</p>
</details> 

- add datetime to migrations/versions/... files
- update README.md
