### ISSUE TITLE
Add MinIO

### ISSUE THREAD

**Issue by birthdaysgift** [fenya123/bingin#16]
**As an Architect I would like to have MinIO object storage to persist our files on backend.**

Before we start to write the implementation of the backend we have to setup main tools we want to use and check that they work correctly. The goal of this story is setting up MinIO and configuring it for all environments (local, ci) and tools (linters, pytest) we use at this moment.

**Acceptance criteria**

- MinIO is added to the repo via docker and docker-compose to local/dev, local/test and ci/test environments
- minio python library and other dependencies needed to work with MinIO from python code are added to the repo as dependencies
- backend app is configured and allows us to connect to minio from our code
- simple model and endpoint are added to check that minio works fine
- simple test is written for that endpoint to check that unit-testing works fine with minio

**Tasks**

- [x] https://github.com/fenya123/acih-backend/issues/65
- [x] https://github.com/fenya123/acih-backend/issues/67
- [x] https://github.com/fenya123/acih-backend/issues/69

**Comment by birthdaysgift** [comment]
Approximate approach to story decomposition:

0. Understand **what** MinIO is and **why** is it used

- run minio in local via docker containers and configure application to work with it

- configure fastapi to work with minio
  - endpoint which adds object to minio
  - endpoint which gets list of objects from minio
  - add config (to not ues hardcoded values)

- integration with pytest
  - setup fixture for minio which will ensure tests independence
  - tests for routes from previous tasks
