### ISSUE TITLE
Post management features

### ISSUE THREAD

**Issue by birthdaysgift** [fenya123/bingin#23]
**As a user I would like to have ability to work and manage my posts and see other users posts on the platform.**

Signed in user should be able to:
- see his own profile posts
- create new posts
- see posts created by other users

Following attributes are required for a new post:
- image file (and preview image as well)

Optional attributes for a new post:
- description
- title

**Tasks**:

- [x] https://github.com/fenya123/acih-backend/issues/89
- [x] https://github.com/fenya123/acih-backend/issues/125
- [x] https://github.com/fenya123/acih-backend/issues/127
- [x] https://github.com/fenya123/acih-backend/issues/128
- [x] https://github.com/fenya123/acih-backend/issues/133
