### ISSUE TITLE
Following management features

### ISSUE THREAD

**Issue by birthdaysgift** [fenya123/bingin#24]
**As a user I would like to have ability to follow/unfollow accounts on the platform and see my followers and followees and followers/followees of other users as well.**

Signed in user should be able to:
- follow/unfollow other users
- see his own followers/followees
- see other user's followers/followees

**Tasks**
- [x] https://github.com/fenya123/acih-backend/issues/91
- [x] https://github.com/fenya123/acih-backend/issues/117
- [x] https://github.com/fenya123/acih-backend/issues/119
- [x] https://github.com/fenya123/acih-backend/issues/121
