### ISSUE TITLE
File upload/download features

### ISSUE THREAD

**Issue by birthdaysgift** [fenya123/bingin#28]
**As a User I need to have an ability to upload/download files while I'm working on the platform.**

Those files could be post images, profile backgrounds and profile avatars.

---

Technical requirements:

Endpoints working with files should be separated from endpoints working with related "domain" features. For example, If a user wants to create a new post, there should be two separate endpoints - one for file upload, and another for post creation. This will allow us to have "domain" endpoints to be consistently looking in terms of request formats. 

If we would decide to upload post file in the same endpoint which creates a post, then this endpoint should accept request body in multipart/form-data, while other endpoints which don't require a file will accept json formatted data. So to avoid this inconsistency between input formats we decided to separate endpoints which work with files and which work with domain data.

**Tasks**
- [x] https://github.com/fenya123/acih-backend/issues/101
- [x] https://github.com/fenya123/acih-backend/issues/107
- [x] https://github.com/fenya123/acih-backend/issues/109
