### ISSUE TITLE
Add linters configuration

### ISSUE THREAD

**Issue by birthdaysgift** [fenya123/bingin#9]
**As an Architect I would like to have a clean and consistent codebase with best practices being used. I would like all code added to the codebase from the beginning to be checked by linters.**

---

**Backend** 

I would like to get a response from linters as soon as possible, so linters rule-scope should be fine grained in the following way - slower linter shouldn't check the rules already implemented in a faster one.

Linters list we need to have in a project:

- **Mypy**
  Should be set up as strict as possible to find all possible typing errors.

- **Ruff**
  Should be set up as strict as possible to find all errors it's able to.

- **Flake8**
  Should be set up as strict as possible except the rules already checked by ruff.

- **Pylint**
  Should be set up as strict as possible except the rules already checked by ruff and flake8.

---

**Frontend**

Some compiler checks may look like linter checks, so compiler checks are in the scope of this story as well as linter checks.

- **Typescript**
  Should be set up as strict as possible to find all possible typing errors.

- **ESLint**
  Should be set up as strict as possible to find all errors it's able to.

- ~~Prettier~~
  We're not going to use prettier, because prettier has a strict opinionated list of rules and doesn't provide flexible configuration. We will use ESLint formatting rules for our codebase instead of prettier.

- **Useful ESLint plugins**
  Research plugins available for ESLint, add and configure the ones useful in our project.

**Tasks BE**

- [x] https://github.com/fenya123/acih-backend/issues/3

**Quickfixes BE**

- [x] https://github.com/fenya123/acih-backend/issues/5

**Tasks FE**

- [x] https://github.com/fenya123/acih-frontend/issues/3
- [x] https://github.com/fenya123/acih-frontend/issues/5
- [x] https://github.com/fenya123/acih-frontend/issues/7
